# Generated by Django 2.2.13 on 2020-07-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_name', models.CharField(max_length=55, null=True, verbose_name='ชื่อย่อ (หน่วยงานระดับกระทรวง)')),
                ('ministry', models.TextField(verbose_name='ชื่อหน่วยงาน ระดับกระทรวง')),
            ],
            options={
                'verbose_name': 'หน่วยงานระดับกระดับกระทรวง',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_name', models.CharField(max_length=55, null=True, verbose_name='ชื่อย่อ (หน่วยงานระดับกรม)')),
                ('department', models.TextField(verbose_name='ชื่อหน่วยงาน ระดับกรม')),
                ('establish', models.CharField(max_length=4, null=True, verbose_name='จัดตั้งเมื่อ (พ.ศ.)')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ministry', to='nwcc.Ministry', verbose_name='สังกัดกระทรวง')),
            ],
            options={
                'verbose_name': 'หน่วยงานระดับกรม',
            },
        ),
    ]
