# Generated by Django 2.2.13 on 2020-07-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwcc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='establish',
            field=models.CharField(max_length=4, null=True, verbose_name='จัดตั้งเมื่อ (พ.ศ.)'),
        ),
    ]
