version: "3"
services:
  nwcc-project-db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5439:5432"
    volumes:
      - ./db_vol:/var/lib/postgresql/data
  nwcc-project-web:
    image: bird50/resource_cat:v2
    #command: python manage.py runserver 0.0.0.0:8000
    command: tail -F anything
    volumes:
      - .:/code
    ports:
      - "8007:8000"
    depends_on:
      - nwcc-project-db
