# Generated by Django 2.2.13 on 2020-07-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nwcc', '0003_auto_20200712_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupActPrb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ชื่อกลุ่มข้อมูล')),
                ('description', models.TextField(null=True, verbose_name='รายละเอียดกลุ่มข้อมูล')),
                ('NumOrder', models.IntegerField(verbose_name='ลำดับที่')),
            ],
            options={
                'verbose_name': 'กลุ่มข้อมูล ตามแผนแม่บท และพรบ.ทรัพยากรน้ำพ.ศ.2561',
                'verbose_name_plural': 'กลุ่มข้อมูล ตามแผนแม่บท และพรบ.ทรัพยากรน้ำพ.ศ.2561',
            },
        ),
        migrations.CreateModel(
            name='Rs_Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อชุดข้อมูล')),
                ('link', models.URLField(blank=True, verbose_name='ลิ๊งค์ที่อยู่ข้อมูล')),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดชุดข้อมูล')),
                ('Time_period', models.TextField(blank=True, verbose_name='ช่วงเวลาของข้อมูล')),
                ('source', models.TextField(blank=True, verbose_name='อธิบายแหล่งข้อมูล')),
                ('type_of_data', models.CharField(choices=[('CSV', 'CSV'), ('TXT', 'Text file'), ('XLS', 'Excel file,xlsx,xls,xl*'), ('SHP', 'ESRI Shape file'), ('ETC', 'Other formats'), ('UNK', 'Unknown format')], default='UNK', max_length=3, verbose_name='รูปแบบชุดข้อมูล')),
                ('date_recived', models.DateTimeField(verbose_name='วันที่ได้รับข้อมูล')),
                ('reference_doc', models.TextField(verbose_name='เอกสารอ้างอิง')),
                ('related_subject', models.TextField(verbose_name='หัวข้อที่เกี่ยวข้อง')),
                ('data_licensing', models.TextField(verbose_name='อธิบายสิทธิของชุดข้อมูล')),
                ('note', models.TextField(verbose_name='โน๊ต')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('GroupActPrb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GroupActPrb', to='rs_cat.GroupActPrb', verbose_name='กลุ่มข้อมูลตามยุทธศาสตร์ และ พรบ.')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agency', to='nwcc.Agency', verbose_name='ชื่อหน่วยงานเจ้าของ/รับผิดชอบข้อมูล (ระดับกรม)')),
                ('agency_provided_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agency_provided_data', to='nwcc.Agency', verbose_name='ชื่อหน่วยงานที่ส่งข้อมูล (ระดับกรม)')),
            ],
            options={
                'verbose_name': 'ชุดข้อมูล',
                'verbose_name_plural': 'ชุดข้อมูล',
            },
        ),
    ]
