# Generated by Django 2.2.13 on 2020-07-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rs_cat',
            name='document01',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='เอกสารประกอบ 1'),
        ),
        migrations.AddField(
            model_name='rs_cat',
            name='document02',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='เอกสารประกอบ 2'),
        ),
        migrations.AddField(
            model_name='rs_cat',
            name='document03',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='เอกสารประกอบ 3'),
        ),
    ]
