# Generated by Django 2.2.13 on 2020-07-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_cat', '0002_auto_20200713_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupactprb',
            options={'ordering': ('NumOrder',), 'verbose_name': 'กลุ่มข้อมูล ตามแผนแม่บท และพรบ.ทรัพยากรน้ำพ.ศ.2561', 'verbose_name_plural': 'กลุ่มข้อมูล ตามแผนแม่บท และพรบ.ทรัพยากรน้ำพ.ศ.2561'},
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='data_licensing',
            field=models.TextField(blank=True, verbose_name='อธิบายสิทธิของชุดข้อมูล'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='date_recived',
            field=models.DateTimeField(blank=True, verbose_name='วันที่ได้รับข้อมูล'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='document01',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='เอกสารประกอบ 1'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='document02',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='เอกสารประกอบ 2'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='document03',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='เอกสารประกอบ 3'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='note',
            field=models.TextField(blank=True, verbose_name='โน๊ต'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='reference_doc',
            field=models.TextField(blank=True, verbose_name='เอกสารอ้างอิง'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='related_subject',
            field=models.TextField(blank=True, verbose_name='หัวข้อที่เกี่ยวข้อง'),
        ),
    ]
