# Generated by Django 2.2.13 on 2020-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_cat', '0003_auto_20200713_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rs_cat',
            name='data_licensing',
            field=models.TextField(blank=True, null=True, verbose_name='อธิบายสิทธิของชุดข้อมูล'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='date_recived',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ได้รับข้อมูล'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='โน๊ต'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='reference_doc',
            field=models.TextField(blank=True, null=True, verbose_name='เอกสารอ้างอิง'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='related_subject',
            field=models.TextField(blank=True, null=True, verbose_name='หัวข้อที่เกี่ยวข้อง'),
        ),
    ]
