# Generated by Django 2.2.13 on 2020-07-16 04:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rs_cat', '0007_auto_20200716_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='rs_cat',
            name='status',
            field=models.CharField(blank=True, choices=[('00', 'รับข้อมูล'), ('01', 'อยู่ระหว่างตรวจสอบ'), ('09', 'ข้อมูลพร้อม!!!')], max_length=2, null=True, verbose_name='สถานะการนำไปใช้งานของข้อมูล'),
        ),
        migrations.AlterField(
            model_name='rs_cat',
            name='GroupActPrb',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G-01', '1) การจัดการน้ำ เพื่ออุปโภคบริโภค'), ('G-02', '2) การจัดการน้ำ เพื่อการเกษตร/ประมง'), ('G-03', '3) การจัดการน้ำ เพื่ออุตสาหกรรม'), ('G-04', '4) การเตือนภัยและจัดการสถานการณ์น้ำท่วม'), ('G-05', '5) การเตือนภัยและจัดการสถานการณ์ภัยแล้ง'), ('G-06', '6) การจัดการคุณภาพน้ำและรักษาระบบนิเวศและอนุรักษ์ทรัพยากรน้ำสาธารณะ'), ('G-07', '7) การอนุรักษ์ฟื้นฟูสภาพป่าต้นน้ำที่เสื่อมโทรมและป้องกันการพังทลายของดิน'), ('G-08', '8) การจัดการแผนงานโครงการด้านทรัพยากรน้ำ'), ('G-09', '9) การจัดการและส่งเสริมนวัตกรรมด้านทรัพยากรน้ำ'), ('G-10', '10) การบริหารจัดการน้ำ'), ('G-11', '11) การอนุญาตใช้น้ำ'), ('G-12', '12) การจัดการผังน้ำ')], max_length=59, null=True, verbose_name='กลุ่มข้อมูลตามยุทธศาสตร์ และ พรบ.ทรัพยากรน้ำ พ.ศ.2561'),
        ),
    ]
